# Generated by Django 6.0.2 on 2026-02-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(max_length=255)),
                ('Picture', models.ImageField(upload_to='projects/')),
                ('Description', models.TextField(max_length=2000)),
                ('Github_link', models.URLField(blank=True, null=True)),
                ('Live_site_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
