# Generated by Django 5.2.5 on 2026-02-08 09:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='Description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Live_site_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
