# Generated by Django 5.2.5 on 2026-02-16 10:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDataMOdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('logo', 'Site Logo'), ('home_heading_skill', 'Home Heading Skill'), ('home_skill_detail', 'Home Short Skill Define'), ('home_pic', 'Home Picture'), ('footer_skill_short', 'Footer Skill'), ('linkedIn_link', 'LinkedIn Link'), ('github_link', 'Github Link main'), ('profile_pic', 'Profile Picture'), ('about_me', 'About Me'), ('email', 'Email'), ('contact_number', 'Contact Number')], max_length=100, unique=True)),
                ('pictures', models.ImageField(null=True, upload_to='')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='text')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, null=True)),
                ('links', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
