# Generated by Django 5.2.5 on 2026-02-16 10:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitedatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedatamodel',
            name='contact_no',
            field=models.CharField(blank=True, default='not define', null=True),
        ),
        migrations.AlterField(
            model_name='sitedatamodel',
            name='email',
            field=models.EmailField(default='not define', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitedatamodel',
            name='links',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='sitedatamodel',
            name='pictures',
            field=models.ImageField(default='not define', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitedatamodel',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='not define', verbose_name='text'),
        ),
    ]
