# Generated by Django 5.2.5 on 2026-02-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitedatamodel_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedatamodel',
            name='email',
            field=models.EmailField(blank=True, default='not define', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitedatamodel',
            name='pictures',
            field=models.ImageField(blank=True, default='not define', null=True, upload_to='site_pics/'),
        ),
    ]
