# Generated by Django 5.2.5 on 2026-02-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sitedatamodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedatamodel',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitedatamodel',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
