# Generated by Django 5.2.5 on 2026-02-18 05:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_educationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='experience',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='text'),
        ),
    ]
