# Generated by Django 5.2.5 on 2026-02-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_educationmodel_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
