# Generated by Django 5.2.5 on 2026-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_educationmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='degree_name',
            field=models.CharField(choices=[('BSc', 'Bachelor of Science'), ('BSSE', 'BS Software Engineering'), ('Intermediate', 'Intermediate'), ('BA', 'Bachelor of Arts'), ('BCom', 'Bachelor of Commerce'), ('BBA', 'Bachelor of Business Administration'), ('MSc', 'Master of Science'), ('MSSE', 'MS Software Engineering'), ('MA', 'Master of Arts'), ('MCom', 'Master of Commerce'), ('MBA', 'Master of Business Administration'), ('PhD', 'Doctor of Philosophy')], max_length=255),
        ),
    ]
