# Generated by Django 5.2.5 on 2026-02-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_educationmodel_degree_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='underconstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_const', models.BooleanField(default=False)),
                ('uc_note', models.TextField(blank=True, help_text='Note for underconstruciton..', null=True)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='End durations for underconstructioin.....', null=True)),
                ('uc_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
