# Generated by Django 6.0.2 on 2026-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_languagesmodel_alter_contactmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedatamodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/'),
        ),
        migrations.AlterField(
            model_name='sitedatamodel',
            name='name',
            field=models.CharField(choices=[('logo', 'Site Logo'), ('home_heading_skill', 'Home Heading Skill'), ('home_skill_detail', 'Home Short Skill Define'), ('home_pic', 'Home Picture'), ('footer_skill_short', 'Footer Skill'), ('linkedIn_link', 'LinkedIn Link'), ('github_link', 'Github Link main'), ('profile_pic', 'Profile Picture'), ('about_me', 'About Me'), ('email', 'Email'), ('contact_number', 'Contact Number'), ('resume', 'Resume')], max_length=100, unique=True),
        ),
    ]
